name: Build and Release Signed AAB and APK

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-android:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: |
          echo $ENCODED_STRING | base64 -di > release.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release AAB and APK
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease assembleRelease

      - name: Prepare Artifacts
        id: prep
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          if [ -z "$TAG_NAME" ]; then
            TAG_NAME="release"
          fi
          AAB_PATH=$(find app/build/outputs/bundle/release -name "*.aab" | head -n 1)
          AAB_FILENAME="trainflow-${TAG_NAME}.aab"
          cp "$AAB_PATH" "$AAB_FILENAME"
          
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          APK_FILENAME="trainflow-${TAG_NAME}.apk"
          cp "$APK_PATH" "$APK_FILENAME"
          
          echo "aab_filename=$AAB_FILENAME" >> $GITHUB_OUTPUT
          echo "apk_filename=$APK_FILENAME" >> $GITHUB_OUTPUT

      - name: Upload Artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.prep.outputs.aab_filename }}
            ${{ steps.prep.outputs.apk_filename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

